version: '3.7'
services:
  chatgpt_api:
    build: chatgpt_api/
    image: slaids/chatgpt_api
    container_name: chatgpt_api
    environment:
      EMAIL: ${CHATGPT_EMAIL}
      PASSWORD: ${CHATGPT_PASSWORD}
      PORT: 8000
    ports:
      - 8000:8000

  postgres:
    image: postgres:12.2
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slaids_db
    ports:
      - 5432:5432
