services:
  chatgpt_api:
    build: ../chatgpt/
    image: slaids/chatgpt_api
    container_name: chatgpt_api
    environment:
      EMAIL: ${EMAIL}
      PASSWORD: ${PASSWORD}
    ports:
      - 8000:80
