version: '3.7'
services:
  chatgpt_api:
    build: chatgpt_api/
    image: slaids/chatgpt_api
    container_name: chatgpt_api
    environment:
      EMAIL: ${EMAIL}
      PASSWORD: ${PASSWORD}
    ports:
      - 8000:80

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
